// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1.Models;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1.Models.DifferenceDataHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("HotelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MassEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MassEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId1");

                    b.HasIndex("MassEventId1");

                    b.HasIndex("UserId1");

                    b.ToTable("DifferenceDataHotel");
                });

            modelBuilder.Entity("Project1.Models.EnteredDataHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("HotelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MassEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MassEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Сapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId1");

                    b.HasIndex("MassEventId1");

                    b.HasIndex("UserId1");

                    b.ToTable("EnteredDataHotel");
                });

            modelBuilder.Entity("Project1.Models.Groups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("MassEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MassEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MassEventId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Project1.Models.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("MassEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MassEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MassEventId1");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Project1.Models.MassEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MassEvents");
                });

            modelBuilder.Entity("Project1.Models.RecordDataHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("HotelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MassEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("MassEventId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId1");

                    b.HasIndex("MassEventId1");

                    b.ToTable("RecordDataHotel");
                });

            modelBuilder.Entity("Project1.Models.Settler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdditionalPeoples")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("preferred_type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settler");
                });

            modelBuilder.Entity("Project1.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project1.Models.UserXHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<Guid?>("HotelId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId1");

                    b.HasIndex("UserId1");

                    b.ToTable("UserXHotels");
                });

            modelBuilder.Entity("Project1.Models.DifferenceDataHotel", b =>
                {
                    b.HasOne("Project1.Models.Hotel", "Hotel")
                        .WithMany("DifferenceDataHotels")
                        .HasForeignKey("HotelId1");

                    b.HasOne("Project1.Models.MassEvent", "MassEvent")
                        .WithMany("DifferenceDataHotels")
                        .HasForeignKey("MassEventId1");

                    b.HasOne("Project1.Models.User", "User")
                        .WithMany("DifferenceDataHotels")
                        .HasForeignKey("UserId1");

                    b.Navigation("Hotel");

                    b.Navigation("MassEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project1.Models.EnteredDataHotel", b =>
                {
                    b.HasOne("Project1.Models.Hotel", "Hotel")
                        .WithMany("EnteredDataHotels")
                        .HasForeignKey("HotelId1");

                    b.HasOne("Project1.Models.MassEvent", "MassEvent")
                        .WithMany("EnteredDataHotels")
                        .HasForeignKey("MassEventId1");

                    b.HasOne("Project1.Models.User", "User")
                        .WithMany("EnteredDataHotel")
                        .HasForeignKey("UserId1");

                    b.Navigation("Hotel");

                    b.Navigation("MassEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project1.Models.Groups", b =>
                {
                    b.HasOne("Project1.Models.MassEvent", "MassEvent")
                        .WithMany("Groups")
                        .HasForeignKey("MassEventId1");

                    b.HasOne("Project1.Models.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MassEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project1.Models.Hotel", b =>
                {
                    b.HasOne("Project1.Models.MassEvent", "MassEvent")
                        .WithMany("Hotels")
                        .HasForeignKey("MassEventId1");

                    b.Navigation("MassEvent");
                });

            modelBuilder.Entity("Project1.Models.RecordDataHotel", b =>
                {
                    b.HasOne("Project1.Models.Hotel", "Hotel")
                        .WithMany("RecordDataHotels")
                        .HasForeignKey("HotelId1");

                    b.HasOne("Project1.Models.MassEvent", "MassEvent")
                        .WithMany("RecordDataHotels")
                        .HasForeignKey("MassEventId1");

                    b.Navigation("Hotel");

                    b.Navigation("MassEvent");
                });

            modelBuilder.Entity("Project1.Models.UserXHotel", b =>
                {
                    b.HasOne("Project1.Models.Hotel", "Hotel")
                        .WithMany("UserXHotels")
                        .HasForeignKey("HotelId1");

                    b.HasOne("Project1.Models.User", "User")
                        .WithMany("UserXHotels")
                        .HasForeignKey("UserId1");

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project1.Models.Hotel", b =>
                {
                    b.Navigation("DifferenceDataHotels");

                    b.Navigation("EnteredDataHotels");

                    b.Navigation("RecordDataHotels");

                    b.Navigation("UserXHotels");
                });

            modelBuilder.Entity("Project1.Models.MassEvent", b =>
                {
                    b.Navigation("DifferenceDataHotels");

                    b.Navigation("EnteredDataHotels");

                    b.Navigation("Groups");

                    b.Navigation("Hotels");

                    b.Navigation("RecordDataHotels");
                });

            modelBuilder.Entity("Project1.Models.User", b =>
                {
                    b.Navigation("DifferenceDataHotels");

                    b.Navigation("EnteredDataHotel");

                    b.Navigation("Groups");

                    b.Navigation("UserXHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
